export const cardStyles = `
  :host { display:block; height:100%; color:#172033; font:13px/1.45 Inter,"PingFang SC","Microsoft YaHei",sans-serif; }
  * { box-sizing:border-box; }
  button,input,select { font:inherit; }
  button { cursor:pointer; }
  button:disabled { cursor:not-allowed; opacity:.42; }
  .robot-card { --teal:#009c91; --blue:#1687ee; height:100%; min-height:640px; display:grid; grid-template-rows:auto auto minmax(0,1fr) auto auto; background:linear-gradient(180deg,#f9fcfd 0,#f4f7fa 100%); border:1px solid #dce5ec; border-radius:15px; overflow:hidden; box-shadow:0 18px 45px rgba(42,66,88,.12); }
  .hero { display:flex; align-items:center; justify-content:space-between; gap:18px; padding:20px 22px 16px; background:rgba(255,255,255,.92); border-bottom:1px solid #e6edf2; }
  .eyebrow,.kicker { margin:0; color:#78909f; font-size:10px; font-weight:800; letter-spacing:.12em; text-transform:uppercase; }
  h1 { margin:3px 0 2px; font-size:17px; letter-spacing:-.01em; }
  .subtitle { margin:0; color:#7c8996; font-size:11px; }
  .hero-actions { display:flex; align-items:center; justify-content:flex-end; flex-wrap:wrap; gap:7px; }
  .badge { display:inline-flex; align-items:center; gap:6px; padding:5px 9px; border:1px solid #dce6ec; border-radius:999px; background:#f6f9fa; color:#63717d; font-size:10px; font-weight:700; white-space:nowrap; }
  .badge i { width:6px; height:6px; border-radius:50%; background:#96a6b2; }
  .badge.ok { color:#15876f; background:#edfbf5; border-color:#c9ecdf; }.badge.ok i{background:#1db58c;box-shadow:0 0 0 3px rgba(29,181,140,.12)}
  .badge.accent { color:#087e78; background:#e9fbf9; border-color:#bfe8e3; }.badge.accent i{background:var(--teal)}
  .badge.danger { color:#b44b4b; background:#fff2f2; border-color:#f4d2d2; }.badge.danger i{background:#d95d5d}
  .tabs { min-height:46px; display:flex; align-items:end; padding:0 20px; background:#fff; border-bottom:1px solid #e2e9ef; }
  .tab { height:46px; padding:0 15px; border:0; border-bottom:2px solid transparent; background:transparent; color:#768592; font-weight:700; }
  .tab.active { color:#087f78; border-color:var(--teal); }
  .revision { margin:0 0 12px auto; color:#6995bd; font-size:10px; background:#eef7ff; border-radius:999px; padding:3px 8px; }
  .content { min-height:0; overflow:auto; padding:16px 18px 18px; scrollbar-width:thin; scrollbar-color:#b8c8d3 transparent; }
  .point-panel,.jog-panel,.monitor,.preview-panel { background:#fff; border:1px solid #e1e8ee; border-radius:11px; box-shadow:0 7px 22px rgba(39,65,87,.055); }
  .section-heading { height:58px; display:flex; align-items:center; justify-content:space-between; padding:0 15px; border-bottom:1px solid #edf1f4; }
  h2,h3 { margin:0; } h2 { font-size:14px; margin-top:2px; } h3 { font-size:12px; }
  .count { color:#2989d8; background:#edf7ff; padding:4px 8px; border-radius:999px; font-size:10px; }
  .point-list { max-height:275px; overflow:auto; padding:9px; background:#f8fafb; }
  .point-row { width:100%; display:grid; grid-template-columns:32px minmax(0,1fr) auto; align-items:center; gap:10px; margin-bottom:6px; padding:9px 11px; text-align:left; border:1px solid #e2e9ee; border-radius:8px; background:#fff; color:inherit; box-shadow:0 2px 7px rgba(54,75,91,.035); }
  .point-row:hover { border-color:#a7cee9; }.point-row.selected { border-color:#48a7ed; background:linear-gradient(90deg,#eff8ff,#f9fcff); box-shadow:inset 3px 0 #1687ee; }
  .point-index { display:grid; place-items:center; width:27px; height:27px; border-radius:50%; color:#84919b; background:#f0f3f5; font-size:11px; }.selected .point-index{color:#fff;background:#1687ee}
  .point-copy { min-width:0; }.point-copy strong,.point-copy small{display:block}.point-copy small{overflow:hidden;color:#95a2ac;font-size:9px;text-overflow:ellipsis;white-space:nowrap}.point-meta{color:#21a37e;font-size:9px;background:#ebfaf5;padding:3px 6px;border-radius:5px}
  .monitor { margin-top:12px; padding:13px 14px 15px; }.monitor-head,.joint-heading{display:flex;justify-content:space-between;color:#71818e;font-size:10px}.monitor h3{margin:10px 0 7px}.monitor h3 small{color:#9aa7b0;font-weight:500;margin-left:6px}.target-rail{margin-top:9px;padding:7px 9px;border:1px solid #d9e8f2;border-radius:7px;background:#f3f9fd;color:#4f7692;font-size:10px;font-weight:700}
  .pose-grid { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:7px; }.pose-value{position:relative;padding:8px 9px;border:1px solid #e2e8ed;border-radius:7px;background:#fbfcfd}.pose-value small{display:block;color:#8e9ba5;font-size:9px}.pose-value strong{font-size:13px}.pose-value span{margin-left:4px;color:#9ca7af;font-size:9px}
  .joint-heading { align-items:center;margin-top:12px;padding-top:10px;border-top:1px solid #edf1f4}.joint-bars{display:grid;gap:5px;margin-top:8px}.joint-bar{display:grid;grid-template-columns:22px minmax(0,1fr) 58px;align-items:center;gap:7px;font-size:9px;color:#75838f}.joint-bar i{height:5px;overflow:hidden;background:#e8eef2;border-radius:99px}.joint-bar b{display:block;height:100%;background:linear-gradient(90deg,#178eea,#28b3d1);border-radius:99px}.joint-bar strong{text-align:right;font-weight:600;color:#5c6d79}
  .preview-joints { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:8px; padding:14px; }
  .preview-joints label { display:grid; gap:4px; color:#6f7f8b; font-size:10px; }
  .preview-joints input { width:100%; padding:6px 8px; border:1px solid #d8e2e8; border-radius:6px; background:#fff; }
  .jog-settings { display:grid;grid-template-columns:repeat(3,1fr);gap:8px;padding:12px 14px;border-bottom:1px solid #edf1f4}.jog-settings label{color:#6f7f8b;font-size:10px}.jog-settings input,.jog-settings select{width:72px;margin-left:5px;padding:5px;border:1px solid #d8e2e8;border-radius:6px;background:#fff}
  .rail-control{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:10px;margin:12px 12px 0;padding:10px 12px;border:1px solid #cfe3ee;border-radius:8px;background:#f5fafc}.rail-control>div{display:flex;align-items:center;gap:10px}.rail-control strong{font-size:11px}.rail-control small{color:#8a99a5;font-size:9px}.rail-control label{color:#6f7f8b;font-size:10px}.rail-control input{width:90px;margin-right:4px;padding:5px;border:1px solid #cfdde6;border-radius:6px;background:#fff}
  .jog-columns{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:12px}.jog-group{padding:10px;border:1px solid #e3eaef;border-radius:8px}.jog-group h3{margin-bottom:8px}.jog-row{display:grid;grid-template-columns:28px minmax(0,1fr) 29px 29px;gap:5px;align-items:center;margin:5px 0}.jog-row small{color:#8e9aa4}.jog-row button{width:29px;height:27px;border:1px solid #cfdce4;border-radius:6px;background:#f6fafc;color:#267baa;font-weight:800}.jog-row button:hover{border-color:#49a9da;background:#eaf7fd}
  .teach-card{display:flex;align-items:flex-start;justify-content:space-between;gap:15px;margin:0 12px 12px;padding:12px;border:1px solid #cde7e2;border-radius:9px;background:#f1fbf9}.teach-card p{margin:3px 0 0;color:#758b89;font-size:9px}.vision-toggle{display:flex;align-items:center;gap:6px;margin-top:8px;color:#4d6d69;font-size:10px}.marker-select{display:block;margin-top:8px;color:#4d6d69;font-size:10px}.marker-select select{margin-left:6px;min-width:220px;padding:4px 6px;border:1px solid #bfd8d3;border-radius:6px;background:#fff}.teach{color:#087d74!important;border-color:#9dd8cf!important;background:#fff!important}
  .vision-panel{background:#fff;border:1px solid #e1e8ee;border-radius:11px;box-shadow:0 7px 22px rgba(39,65,87,.055);padding:0 0 12px}.vision-summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:12px 14px;border-bottom:1px solid #edf1f4}.vision-summary div{padding:8px 9px;border:1px solid #e2e8ed;border-radius:7px;background:#fbfcfd}.vision-summary small{display:block;color:#8e9ba5;font-size:9px}.vision-summary strong{font-size:11px}.vision-actions{display:flex;flex-wrap:wrap;gap:8px;padding:12px 14px;border-bottom:1px solid #edf1f4}.marker-list{padding:10px 14px 4px}.marker-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:4px 10px;padding:8px 0;border-bottom:1px solid #edf1f4}.marker-row strong{font-size:11px}.marker-row small{color:#8e9aa4}.marker-row span{color:#21a37e;font-size:9px;white-space:nowrap}
  .calibration-meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:0 14px 12px}.calibration-meta div{padding:8px 9px;border:1px solid #e2e8ed;border-radius:7px;background:#fbfcfd}.calibration-meta small{display:block;color:#8e9ba5;font-size:9px}.calibration-meta strong{font-size:10px;word-break:break-all}.calibration-note,.calibration-readonly{margin:0 14px 12px;color:#758b89;font-size:10px;line-height:1.45}.calibration-assets{display:grid;gap:8px;padding:0 14px 12px}.calibration-assets div{padding:8px 9px;border:1px solid #e2e8ed;border-radius:7px;background:#fbfcfd}.calibration-assets small{display:block;color:#8e9ba5;font-size:9px}.calibration-assets strong{font-size:10px;word-break:break-all}.calibration-readonly{display:flex;align-items:center;gap:8px}
  .command-bar{display:flex;align-items:center; justify-content:space-between;gap:10px;padding:11px 18px;background:#fff;border-top:1px solid #e1e9ee}.exclusive-controls,.command-actions{display:flex;gap:7px}.button{min-height:32px;padding:0 12px;border-radius:7px;border:1px solid #d3dee5;background:#fff;color:#536674;font-weight:700;font-size:11px}.button.compact{min-height:27px;padding:0 9px;font-size:10px}.button.primary{min-width:128px;color:#fff;border-color:#008e84;background:linear-gradient(135deg,#00aa9d,#008b83);box-shadow:0 5px 13px rgba(0,150,139,.22)}.button.danger{color:#b44b4b;border-color:#f0c8c8;background:#fff7f7}.button.ghost:hover{border-color:#99bbc9;background:#f5fafb}
  .message{min-height:28px;margin:0;padding:7px 18px;color:#58807d;background:#eff9f7;border-top:1px solid #dcefeb;font-size:10px}.message.error{color:#af4949;background:#fff1f1;border-color:#f2d1d1}.spinner{display:inline-block;width:10px;height:10px;margin-right:6px;border:2px solid rgba(255,255,255,.4);border-top-color:#fff;border-radius:50%;animation:spin .8s linear infinite;vertical-align:-1px}
  .empty{padding:28px;text-align:center;color:#97a5af}.compact-empty{padding:12px}@keyframes spin{to{transform:rotate(360deg)}}
  @media(max-width:760px){.hero{align-items:flex-start}.hero-actions{max-width:230px}.jog-columns{grid-template-columns:1fr}.jog-settings{grid-template-columns:1fr 1fr}.command-bar{align-items:stretch;flex-direction:column}.exclusive-controls,.command-actions{justify-content:flex-end}.content{padding:12px}.robot-card{min-height:600px}}
`
